name: Sync README to Index
on:
  push:
    paths:
      - 'README.md'
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Pandoc (专业Markdown转换工具)
        run: sudo apt-get install pandoc

      - name: Generate index.html
        run: |
          # 生成完整HTML框架（严格匹配截图风格）
          pandoc README.md -f markdown -t html \
            --template='
            <!DOCTYPE html>
            <html>
            <head>
              <title>智脑时代周刊</title>
              <style>
                body { 
                  font-family: -apple-system, sans-serif;
                  max-width: 800px;
                  margin: 0 auto;
                  padding: 20px;
                  background: white;
                }
                h1 { 
                  color: black;
                  text-align: center;
                  border-bottom: none;
                }
                h2 {
                  color: #0366d6;
                  font-size: 1.2em;
                  margin-top: 1.5em;
                }
                ul {
                  padding-left: 1.5em;
                }
                li {
                  list-style-type: "• ";
                  margin-bottom: 0.5em;
                }
                a {
                  color: #0366d6;
                  text-decoration: none;
                }
              </style>
            </head>
            <body>
              <h1>智脑时代周刊</h1>
              {{ content }}
            </body>
            </html>
            ' \
            -o docs/index.html

          # 修复链接格式（确保与README.md完全一致）
          sed -i 's|<a href="$.*$">|<a href="\1" target="_blank">|g' docs/index.html

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/index.html
          git commit -m "Auto-sync README.md to index.html"
          git push
