# Workflow 名称
name: Sync README.md to index.html

# 触发 workflow 的事件
on:
  push:
    branches:
      - main # 请将 'main' 替换为您仓库的默认分支名，例如 master
    paths:
      - README.md # 只在 README.md 文件发生变化时触发

# 定义作业 (jobs)
jobs:
  sync:
    # 在最新的 Ubuntu 环境上运行作业
    runs-on: ubuntu-latest

    # 作业步骤
    steps:
    - name: Checkout 代码
      # 使用 actions/checkout@v4 检出仓库代码
      uses: actions/checkout@v4

    - name: 安装 pandoc
      # 使用 apt-get 在 Ubuntu 环境中安装 pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: 将 README.md 转换为 index.html
      # 使用 pandoc 工具将 Markdown 文件转换为 HTML
      run: |
        pandoc README.md -s -o index.html

    - name: 自动提交并推送 changes 到 index.html
      # 使用 stefanzweifel/git-auto-commit-action@v5 自动提交生成的 index.html 文件
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        # 提交消息
        commit_message: Sync README.md to index.html
        # 指定要提交的文件，这里是新生成的或修改的 index.html
        files: index.html
        # 可选：设置提交作者信息
        # commit_user_name: Automated Sync
        # commit_user_email: actions@github.com
